apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ghcr.io/laurint0/lab-k8s/web:dc88bb7f86f759690af160f5fe9e58ffc74523a6
        ports:
        - containerPort: 80
        - containerPort: 443
 
