apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ghcr.io/laurint0/lab-k8s/web:fc5d48d6b9593d7f9025126d2fbbf708322246cd
        ports:
        - containerPort: 80
        - containerPort: 443
 
